packages:
  - "."
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides: 
  "@tiptap/core": "3.27.1"
  "@tiptap/pm": "3.27.1"
    